# SPDX-License-Identifier: MIT
# Copyright (c) 2024 Marko Sarunac
#
# Part of the Orion's Belt project.
# Repository: https://github.com/Expiscor-Group-Ltd/orions-belt
# Handler ID: OB-008-H

# Network security handlers
# This handler file is used by OB-008 (configure_firewall_tasks.yml)

---
- name: reload nftables
  systemd:
    name: nftables
    state: reloaded
  when: ansible_os_family == "Debian"

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
  when: ansible_os_family == "Debian" 